import vertexai
from vertexai.generative_models import GenerativeModel, Tool, grounding
from google.auth import default
import streamlit as st
import subprocess

# Initialize Vertex AI
PROJECT_ID = "mlds-cap-2024-lexlead-advisor"
REGION = "us-central1"
vertexai.init(project=PROJECT_ID, location=REGION)

# Authentication
credentials, project = default()

# Load Generative Model (e.g., Gemini)
try:
    generative_model = GenerativeModel("gemini-1.5-pro-002")
except Exception as e:
    print(f"Error loading model: {str(e)}")
    exit()

def call_google_search_script():
    """
    Calls an external Python script (`google_search.py`) to perform a Google search.

    Returns:
        str: The output of the Google search script if successful.
        None: If there was an error during execution.
    """
    try:
        result = subprocess.run(['python3', 'google_search.py'], capture_output=True, text=True)
        if result.returncode == 0:
            print(result.stdout)
            return result.stdout
        else:
            print(f"Error executing google_search.py: {result.stderr}")
            return None
    except Exception as e:
        print(f"Exception occurred while calling google_search.py: {str(e)}")
        return None

def clean_grounding_response(response):
    """
    Cleans the grounding response to remove extra lines and spaces for better readability.

    Args:
        response (str): The raw response to clean.

    Returns:
        str: A cleaned version of the response, or the string representation if the input is not a string.
    """
    if isinstance(response, str):
        cleaned_response = " ".join([line.strip() for line in response.splitlines() if line.strip()])
        return cleaned_response
    else:
        return str(response)

def generate_google_search_response(prompt):
    """
    Generates a response using the Google Search Retrieval Tool and the Gemini model.

    Args:
        prompt (str): The prompt to send to the model.

    Returns:
        str: The cleaned response generated by the tool.
        None: If an error occurred or no valid response was generated.
    """
    try:
        # Create Google Search Retrieval Tool
        tool = Tool.from_google_search_retrieval(grounding.GoogleSearchRetrieval())
    except AttributeError as e:
        print(f"Error creating Google Search Retrieval Tool: {str(e)}")
        return None

    try:
        # Generate response using the tool
        response = generative_model.generate_content(prompt, tools=[tool])
        if hasattr(response, 'candidates'):
            for candidate in response.candidates:
                cleaned_content = clean_grounding_response(candidate.content.parts[0])
                return cleaned_content
        else:
            print("No valid response candidates found.")
            return "No valid response candidates found."
    except Exception as e:
        print(f"Error generating content: {str(e)}")
        return None
