name: Python application

on:
  push:
  pull_request:
  workflow_dispatch:


env:
  GCP_PROJECT_ID: mlds-cap-2024-lexlead-advisor
  REGION: us-central1
  SERVICE_NAME: lexlead-streamlit-demo


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install
      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install the project
        run: uv sync --all-extras --dev
  docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker us-docker.pkg.dev --quiet

        - name: Build Docker image
          run: docker build -t us-docker.pkg.dev/$GCP_PROJECT_ID/nu-lexlead-demo/lexlead-streamlit-demo:$GITHUB_SHA .

        - name: Push Docker image
          if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
          run: docker push us-docker.pkg.dev/$GCP_PROJECT_ID/nu-lexlead-demo/lexlead-streamlit-demo:$GITHUB_SHA
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if tests directory exists
        id: check_directory
        run: echo "::set-output name=exists::$(if [ -d "./tests" ]; then echo true; else echo false; fi)"

      - name: Run tests
        if: steps.check_directory.outputs.exists == 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest
          pytest ./tests
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    needs: docker
    env:
      DEPLOY_ENV: production
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME --image us-docker.pkg.dev/mlds-cap-2024-lexlead-advisor/nu-lexlead-demo/lexlead-streamlit-demo:$GITHUB_SHA --region $REGION --platform managed

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: $GCP_PROJECT_ID
          install_components: 'beta'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image us-docker.pkg.dev/$GCP_PROJECT_ID/nu-lexlead-demo/lexlead-streamlit-demo:$GITHUB_SHA \
            --region $REGION \
            --platform managed
            --set-env-vars {{ secrets.APP_DEPLOY_ENV }}
